app_key: <%= ENV["DB_APP_KEY"] %>
app_secret: <%= ENV["DB_APP_SECRET"] %>
access_token: <%= ENV["DB_ACCESS_TOKEN"] %>
access_token_secret: <%= ENV["DB_TOKEN_SECRET"] %>
user_id: <%= ENV["DB_USER_ID"] %>
access_type: "app_folder"
